spring.application.name=datosmedicos

server.port=8083

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://host.docker.internal:3306/datos_medicos}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cuidadoseguro}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

auth.url=http://api-gateway-1937747119.us-east-1.elb.amazonaws.com:8080/auth/validate

spring.rabbitmq.listener.simple.auto-startup=false
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect